# ==========================
# Build Stage
# ==========================
FROM node:20-alpine AS builder

# Set working directory
WORKDIR /usr/src/app

# Copy only package files first (cache dependencies)
COPY apps/web/package.json apps/web/package-lock.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the web app source code
COPY apps/web ./

# Build the Next.js app (standalone output)
RUN npm run build

# ==========================
# Production Stage
# ==========================
FROM node:20-alpine AS runner

WORKDIR /usr/src/app

ENV NODE_ENV=production
ENV PORT=3000

# Copy standalone server and static assets generated by Next.js
COPY --from=builder /usr/src/app/.next/standalone ./
COPY --from=builder /usr/src/app/.next/static ./.next/static
COPY --from=builder /usr/src/app/public ./public

EXPOSE 3000

CMD ["node", "server.js"]