name: Build and deploy Node.js app to Azure Web App - cargoconnect-api

on:
  push:
    branches:
      - preprod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # ✅ INSTALL ONLY API
      - name: Install dependencies
        working-directory: apps/api
        run: npm install

      # ✅ BUILD ONLY API
      - name: Build API
        working-directory: apps/api
        run: npm run build

      # ✅ Upload ONLY API folder
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-app
          path: apps/api

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_05D2638FAEF14B378542350453EBD612 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E345F4FA0AD145BA87B1956933A17583 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8E78E4158EC8489889F0B78A22BBB21A }}

      # ✅ DEPLOY ONLY API
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cargoconnect-api'
          slot-name: 'Production'
          package: .
